SELECT * FROM ACCOUNT;

--1.
SELECT * FROM ACCOUNT WHERE USER_SEQ = 111;

--2.
SELECT * FROM ACCOUNT WHERE BALANCE < 5000;

--3.
SELECT * FROM ACCOUNT
WHERE BALANCE BETWEEN 5000 AND 10000;

--4.
SELECT * FROM ACCOUNT
WHERE ACCOUNT_NUMBER LIKE '%4%';

--5.
SELECT * FROM USERS
WHERE NAME LIKE '삼%';

--6.
SELECT DISTINCT(USER_SEQ) FROM ACCOUNT;

--7.
SELECT * FROM ACCOUNT
WHERE BALANCE IS NULL;

--8.
SELECT * FROM ACCOUNT
WHERE USER_SEQ IS NOT NULL;

--9.
SELECT * FROM ACCOUNT
WHERE USER_SEQ IS NOT NULL
AND
BALANCE <= 4000;

--10.
SELECT * FROM ACCOUNT
ORDER BY USER_SEQ;

--11.
SELECT * FROM ACCOUNT
ORDER BY USER_SEQ, BALANCE DESC;

--12.
SELECT NVL(BALANCE, 0) FROM ACCOUNT;

--13.
SELECT USER_SEQ, NAME, SUBSTR(EMAIL,1,INSTR(EMAIL, '@')-1) AS EMAIL_ID, PHONE, IS_SLEEP
FROM USERS;

--14.
SELECT USER_SEQ, NAME, EMAIL, REPLACE(PHONE, '-', '') AS PHONE_SHORT, IS_SLEEP
FROM USERS;

--15.
SELECT * FROM ACCOUNT WHERE USER_SEQ = 222;


--16.
SELECT SUM(BALANCE) AS BALANCE_SUM 
FROM ACCOUNT;

--17.
SELECT MIN(BALANCE) AS BALANCE_MIN, MAX(BALANCE) AS BALANCE_MAX
FROM ACCOUNT;

--18.
SELECT USER_SEQ, COUNT(ACCOUNT_NUMBER) AS USER_ACCOUNT_CNT
FROM ACCOUNT
WHERE USER_SEQ IS NOT NULL
GROUP BY USER_SEQ;

--19.
SELECT USER_SEQ, SUM(BALANCE) AS USER_BALANCE_SUM
FROM ACCOUNT
WHERE USER_SEQ IS NOT NULL
GROUP BY USER_SEQ;

--20.
SELECT USER_SEQ, SUM(BALANCE) AS USER_BALANCE_SUM
FROM ACCOUNT
WHERE USER_SEQ IS NOT NULL
GROUP BY USER_SEQ
HAVING SUM(BALANCE) <=10000;
