-- MySQL
SELECT B.BOOK_ID, A.AUTHOR_NAME, 
DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK B JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE;


--  도서 ID가 2, 3인 도서에 해당하지 않는듯..?
